package Fun.Absyn; // Java Package generated by the BNF Converter.

public abstract class Main implements java.io.Serializable {
  public abstract <R,A> R accept(Main.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Fun.Absyn.DMain p, A arg);

  }

}
