package CPP.Absyn; // Java Package generated by the BNF Converter.

public class EId extends Exp {
  public final String id_;
  public EId(String p1) { id_ = p1; }

  public <R,A> R accept(CPP.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.EId) {
      CPP.Absyn.EId x = (CPP.Absyn.EId)o;
      return this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return this.id_.hashCode();
  }


}
