package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SIfElse extends Stm {
  public final Exp exp_;
  public final Stm stm_1, stm_2;
  public SIfElse(Exp p1, Stm p2, Stm p3) { exp_ = p1; stm_1 = p2; stm_2 = p3; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SIfElse) {
      CPP.Absyn.SIfElse x = (CPP.Absyn.SIfElse)o;
      return this.exp_.equals(x.exp_) && this.stm_1.equals(x.stm_1) && this.stm_2.equals(x.stm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_.hashCode())+this.stm_1.hashCode())+this.stm_2.hashCode();
  }


}
